#!/usr/bin/env ruby

WHITELIST_COMMANDS = %(create_parking_lot park leave status log).freeze

# args
require 'tty-prompt'

require_relative 'lib/vendors/string'
require_relative 'lib/parking_lot'
require_relative 'lib/helpers'
Dir.glob(File.expand_path('lib/args/*.rb', __dir__)).each do |file|
  require_relative file
end

parking_lot = ParkingLot.new
prompt = TTY::Prompt.new

if ARGV.length.zero?
  # example: interactive
  loop do
    begin
      raw_input = prompt.ask('Input:')
      input = raw_input.split
      cmd = input[0]
      break unless WHITELIST_COMMANDS.include?(cmd)

      prompt.say(process(cmd, input, parking_lot))
    rescue StandardError => e
      prompt.say(e)
    end
  end

else
  # example: file
  File.readlines(ARGV[0]).each do |line|
    next if line.strip == ""

    begin
      input = line.split
      cmd = input[0]
      break unless WHITELIST_COMMANDS.include?(cmd)

      puts process(cmd, input, parking_lot)
    rescue StandardError => e
      puts e.message
    end
  end

end
